### ISSUE TITLE
Libexec support ?

### ISSUE THREAD

**Issue by zGrEaNz** [jakeajames/rootlessJB#1]
Old RootlessJB doesn't work with libexec like AFC2 or Filza

Or it supported, but i don't know : )

**Comment by jakeajames** [comment]
AFC2 contains post install scripts so I'll probably bundle it with the jailbreak until and if a rootless package manager exists, as for "libexec" support I could do that, along with patching daemon plists (as libexec is usually used for daemons). Whilst, Filza works out of the box, discard everything except the .app, install it normally, give it setuid permissions, chown as root and use iSuperSU to give it root code execution
