### ISSUE TITLE
Cannot success with iPhone6 12.2

### ISSUE THREAD

**Issue by retX0** [jakeajames/rootlessJB#23]
I tried this project with my iPhone6, but when tried to call `proc_of_pid` always failed, because it cannot read any data from address where `Find_allproc` returned address. And in 12.2 kernel, there has none symbol with kernelcache, Any idea ?

**Comment by jakeajames** [comment]
rootlessJB doesn't officially support anything newer than 12.1.2

Il giorno martedì 17 dicembre 2019, xnxin <notifications@github.com> ha
scritto:

**Comment by retX0** [comment]
Sorry, It's rootlessJB4 which support 12.0-12.2 & 12.4, not rootlessJB, But thanks for yout reply.
