### ISSUE TITLE
Error building the Xcode project

### ISSUE THREAD

**Issue by TnnsBeast** [jakeajames/rootlessJB#5]
I am getting this error when I try to build the project

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What should I do?

**Comment by ghost** [comment]
same. not been able to compile it correctly yet

**Comment by xxthepersonx** [comment]
@TnnsBeast @p0sin 
Try compiling using a script. I was lazy and just modified Houdini's compiling script from [here](https://github.com/cheesecakeufo/houdini-public/blob/master/compile.sh)

use this code: `#!/bin/bash
echo "[*] Compiling RootlessJB.."
$(which xcodebuild) clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -sdk `xcrun --sdk iphoneos --show-sdk-path` -arch arm64
mv build/Release-iphoneos/rootlessJB.app rootlessJB.app
mkdir Payload
mv rootlessJB.app Payload/rootlessJB.app
echo "[*] Zipping into .ipa"
zip -r9 RootlessJB.ipa Payload/rootlessJB.app
rm -rf build Payload
echo "[*] Done! Install .ipa with Impactor"`

run your "compile.sh" in terminal and you can install the iPad via Xcode 

Edit: sorry about the formatting of the comment... basically you just replace "houdini" with "rootlessJB" and you'll be good

**Comment by TnnsBeast** [comment]
@xxthepersonx so for the (which Xcode build) would I just replace the line $(10.14) or $10.14

idk if my build is actually 10.14 but you know what I mean

**Comment by Skittyblock** [comment]
Well, for one, you should be compiling to your device and not the simulator. Anyways, there's an issue with the project where the voucher_swap folder isn't linked (well, that was my problem and is probably yours too). You just have to go in and add the folder by right clicking and selecting add files. Make sure the create group option is selected when adding the folder or it still won't work.

**Comment by wstclzy2010** [comment]
same problem,I can't complie

**Comment by jakeajames** [comment]
do not run for the simulator lol, choose your ios device

**Comment by TnnsBeast** [comment]
I did though..

**Comment by gellis12** [comment]
Unless you're using the world's first x86_64 iPhone, you tried to build for the iOS simulator.
